#monitor=,preferred,auto,auto
monitor = desc: LG Electronics LG UltraFine 906NTKFBM821, 3200x1800@60.00Hz, 0x0, 1
monitor = desc: Apple Computer Inc Color LCD, disabled
monitor = DP-4, disabled
# monitor = desc:Samsung Electric Company S24E450 H4ZM400778, preferred, auto-center-left, 0.625, transform, 3
monitor = desc:Samsung Electric Company S24E450 H4ZM401288, preferred, auto-center-right, 1, transform, 1
